/**
 * TYPES — surface: `any` is the failure that hides every other one. It satisfies every assertion
 * a consumer writes, so a signature that quietly widens to it ships as a silent breaking change —
 * the unit suite stays green while every caller loses their checks. Every export is asserted here,
 * once, so a new one cannot be added to src/index.ts without a matching line.
 */
import { expectTypeOf } from 'expect-type'
import * as toolkit from '../../src'

expectTypeOf(toolkit.appendChildren).not.toBeAny()
expectTypeOf(toolkit.arrayChunks).not.toBeAny()
expectTypeOf(toolkit.arrayColumns).not.toBeAny()
expectTypeOf(toolkit.arrayDepth).not.toBeAny()
expectTypeOf(toolkit.associativeSlice).not.toBeAny()
expectTypeOf(toolkit.canonicalize).not.toBeAny()
expectTypeOf(toolkit.coerceStringArray).not.toBeAny()
expectTypeOf(toolkit.copyToClipboard).not.toBeAny()
expectTypeOf(toolkit.deleteCookie).not.toBeAny()
expectTypeOf(toolkit.deleteFile).not.toBeAny()
expectTypeOf(toolkit.downloadBlob).not.toBeAny()
expectTypeOf(toolkit.eventDelegate).not.toBeAny()
expectTypeOf(toolkit.extractErrorMessage).not.toBeAny()
expectTypeOf(toolkit.formatCurrency).not.toBeAny()
expectTypeOf(toolkit.formatDateTime).not.toBeAny()
expectTypeOf(toolkit.formatDuration).not.toBeAny()
expectTypeOf(toolkit.formatFileSize).not.toBeAny()
expectTypeOf(toolkit.formatFlag).not.toBeAny()
expectTypeOf(toolkit.formatNodeList).not.toBeAny()
expectTypeOf(toolkit.formatText).not.toBeAny()
expectTypeOf(toolkit.getCookie).not.toBeAny()
expectTypeOf(toolkit.getDelta).not.toBeAny()
expectTypeOf(toolkit.getElementCenter).not.toBeAny()
expectTypeOf(toolkit.getExecTime).not.toBeAny()
expectTypeOf(toolkit.getForm).not.toBeAny()
expectTypeOf(toolkit.getIframe).not.toBeAny()
expectTypeOf(toolkit.getIndex).not.toBeAny()
expectTypeOf(toolkit.getJson).not.toBeAny()
expectTypeOf(toolkit.getMapDistance).not.toBeAny()
expectTypeOf(toolkit.getOverlapRange).not.toBeAny()
expectTypeOf(toolkit.getSiblings).not.toBeAny()
expectTypeOf(toolkit.getUrlQueries).not.toBeAny()
expectTypeOf(toolkit.getUuid).not.toBeAny()
expectTypeOf(toolkit.getValue).not.toBeAny()
expectTypeOf(toolkit.isAcceptedFileType).not.toBeAny()
expectTypeOf(toolkit.isInViewport).not.toBeAny()
expectTypeOf(toolkit.isJson).not.toBeAny()
expectTypeOf(toolkit.isWithinFileSize).not.toBeAny()
expectTypeOf(toolkit.levenshteinDistance).not.toBeAny()
expectTypeOf(toolkit.match).not.toBeAny()
expectTypeOf(toolkit.rangeOverlaps).not.toBeAny()
expectTypeOf(toolkit.secondsToTime).not.toBeAny()
expectTypeOf(toolkit.setCookie).not.toBeAny()
expectTypeOf(toolkit.setUrlQueries).not.toBeAny()
expectTypeOf(toolkit.timeToSeconds).not.toBeAny()
expectTypeOf(toolkit.toFormData).not.toBeAny()
